### ISSUE TITLE
NullpointerException

### ISSUE THREAD

**Issue by ChristianRomberg** [InfectionChain/InfectionChain-Android#2]
https://github.com/Bandemic/Bandemic-Android/blob/f6551e31471ba33dc0aca7e39867709fe02f33e2/app/src/main/java/com/example/infectiontracker/ui/InfectedUUIDsAdapter.java#L46

infectedUUIDs is null on first app start

**Comment by hermlon** [comment]
gelöst durch https://github.com/Bandemic/Bandemic-Android/blob/c88edf7e66e556a7e1f9175fe4804de19e2fddac/app/src/main/java/app/bandemic/ui/InfectedUUIDsAdapter.java#L22
